### PR TITLE
Added some simple CSS

### PR DESCRIPTION
**Pull request by sarupbanskota**
Hello, I'm a student from India. I'm very new to Open Source and wanted to lend a hand and learn. I've done some CSS work as I found this page to be currently pure HTML. I can probably do better, but I guess this is a start? :) It's responsive.
(Bootstrap powered. Requires additional content to be added to the boxes)

### CODE REVIEW

**Comment by anantn** [comment]
Hey @sarupbanskota, thanks for the patch - the page looks ncie! Couple of comments:
- Could you revert the text to be what was on the original page? For eg: title should be "WebRTC Test Landing Page" and the subtitle needs to be fixed too.
- Your changes breaks the feature detection, I still get three boxes warning me that I don't have WebRTC enabled (but I do). Make sure to test your page on various versions of Firefox (Beta, Aurora & Nightly).

**Comment by sarupbanskota** [comment]
Sure @anantn, I can revert the text back to original. I'm not sure why the feature detection would break, as I only added CSS, but I will surely look at it :)

**Comment by sarupbanskota** [comment]
@anantn, I found the problem, it's now fixed :)

**Comment by sarupbanskota** [comment]
@anantn I guess you could perform the merge now? Thanks!

**Comment by anantn** [comment]
@sarupbanskota, the pull request cannot be automatically merged, could you pull from master again and merge your changes?

**Comment by makkes** [comment]
It would be preferable to include minified bootstrap files.

**Comment by sarupbanskota** [comment]
@Makkes Sure. I'll add minfiy those files :)

**Comment by anantn** [comment]
Superseded by pull request #2.

**Pull request closed without merging**
